### ISSUE TITLE
Using raw doesn't unpack variables

### ISSUE THREAD

**Issue by eldoy** [eldoy/flekk#12]
```yml
test$get:
  type: text
  account_id: $account.id
```

This literally tests for $account.id, not the value of account id. Raw needs to be unpacked. Should use val and then display raw?
