### ISSUE TITLE
Pass params to setup functions?

### ISSUE THREAD

**Issue by eldoy** [eldoy/flekk#5]
Allow objects to pass params to setup function:

```yaml
setup:
  create-account:
    name: Test
    email: test@7i.no
```
