### ISSUE TITLE
Data files?

### ISSUE THREAD

**Issue by eldoy** [eldoy/flekk#8]
`users.data.yml`? Data to be merged:

```yml
# Direct
data$users: users
$users

# Multiple
data$data: 
  - users
  - projects

$data.users
```
